//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullancılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullancılar()
        {
            this.Oyuncular = new HashSet<Oyuncular>();
        }
    
        public int kullanıcıID { get; set; }
        public string kullaniciAdı { get; set; }
        public string şifre { get; set; }
        public string ePosta { get; set; }
        public Nullable<int> yetkiTürüID { get; set; }
    
        public virtual YetkiTürleri YetkiTürleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oyuncular> Oyuncular { get; set; }
    }
}
