//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maçlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maçlar()
        {
            this.MaçDetay = new HashSet<MaçDetay>();
        }
    
        public int maçID { get; set; }
        public int turnuvaID { get; set; }
        public Nullable<int> takım1ID { get; set; }
        public Nullable<int> takım2ID { get; set; }
        public Nullable<System.DateTime> maçTarihi { get; set; }
        public string sonuç { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaçDetay> MaçDetay { get; set; }
        public virtual Takımlar Takımlar { get; set; }
        public virtual Takımlar Takımlar1 { get; set; }
        public virtual Turnuvalar Turnuvalar { get; set; }
    }
}
