//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncular
    {
        public int oyuncuID { get; set; }
        public Nullable<int> takımID { get; set; }
        public Nullable<int> kullanıcıID { get; set; }
    
        public virtual Kullancılar Kullancılar { get; set; }
        public virtual Takımlar Takımlar { get; set; }
    }
}
